---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-{{ .Release.Name }} 
  annotations:
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": "{{ .Release.Namespace }}"
spec:
  ingressClassName: nginx
  rules:
    - host: kuberlab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}-{{ .Release.Name }}
                port:
                  number: 80
