---
apiVersion: v1
kind: Service
metadata:
  name: front-svc-{{ .Release.Name }}
  annotations:
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": "{{ .Release.Namespace }}"
spec:
  selector:
    app: nginx
  ports:
    - name: front
      protocol: TCP
      port: 80
      targetPort: 80
