---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: nfs-tool
  template:
    metadata:
      labels:
        app: nfs-tool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: nfs-storage
              mountPath: /mnt/nfs
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
