---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: vol-test
  template:
    metadata:
      labels:
        app: vol-test
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'while true; do echo Hello! > /data/share.txt; sleep 5; done']
          volumeMounts:
            - name: volume-test
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool
          command: ['sh', '-c', 'while true; do cat /data/share.txt; sleep 5;  done']
          volumeMounts:
            - name: volume-test
              mountPath: /data
      volumes:
        - name: volume-test
          emptyDir: {}
